[package]
name = "cerebro_music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.7"
songbird = { version = "0.3.2", features = ["yt-dlp", "builtin-queue", "serenity", "tokio"] }
tokio = { version = "1.33.0", features = ["rt-multi-thread"] }
